import Foundation

// Emoji search, for the launcher's `emoji <text>`. The data is EmojiData.swift, generated by
// scripts/generate-emoji-data.swift from Unicode's emoji-test.txt and CLDR's English annotations.

/// One emoji and the words it's found by.
public struct EmojiEntry: Sendable {
    public let emoji: String
    /// The Unicode name, lowercase: "face with tears of joy".
    public let name: String
    /// `name`'s words, folded the way queries are, and the `Character` offset of each in `name`.
    let nameWords: [String]
    let nameWordOffsets: [Int]
    /// Folded CLDR keywords that aren't name words, plus joined forms like "thumbsup".
    let keywords: [String]
    /// `nameWords` joined by spaces, compared with the whole query.
    let normalizedName: String
    /// Position in the data, the last tie-break.
    let order: Int
}

/// An emoji that matched a query.
public struct EmojiMatch: Sendable {
    public let entry: EmojiEntry
    public let score: Double
    /// `Character` offsets in `entry.name` of the matched name-word prefixes, for highlighting.
    public let titlePositions: [Int]
    /// When a query word matched only keywords: the first such keyword, e.g. "tada" for 🎉.
    public let matchedKeyword: String?
}

/// Every emoji this Mac draws, searched by word prefix. Immutable: the launcher parses one when an
/// emoji search starts and drops it when the panel closes.
public struct EmojiIndex: Sendable {
    public let entries: [EmojiEntry]

    /// Parses the bundled data.
    public static func load() -> EmojiIndex {
        EmojiIndex(data: EmojiData.text)
    }

    /// The frecency id an emoji's uses are recorded under.
    public static func frecencyID(for emoji: String) -> String {
        "emoji:\(emoji)"
    }

    /// Lines of `emoji<TAB>name<TAB>space-separated search words`; other lines are skipped.
    public init(data: String) {
        var entries: [EmojiEntry] = []
        entries.reserveCapacity(2_048)
        for line in data.utf8.split(separator: UInt8(ascii: "\n")) {
            let fields = line.split(separator: UInt8(ascii: "\t"), maxSplits: 2, omittingEmptySubsequences: false)
            guard fields.count >= 2, !fields[0].isEmpty, !fields[1].isEmpty else { continue }
            let name = String(decoding: fields[1], as: UTF8.self)
            let (words, offsets) = Self.words(in: name)
            let keywords = fields.count > 2
                ? fields[2].split(separator: UInt8(ascii: " ")).map { String(decoding: $0, as: UTF8.self) }
                : []
            entries.append(EmojiEntry(
                emoji: String(decoding: fields[0], as: UTF8.self),
                name: name,
                nameWords: words,
                nameWordOffsets: offsets,
                keywords: keywords,
                normalizedName: words.joined(separator: " "),
                order: entries.count
            ))
        }
        self.entries = entries
    }

    /// Emoji with a name or keyword word starting with every query word, best first, with
    /// frecency blended in as the ranker does. An empty query lists the frecent emoji, then the
    /// rest in data order.
    public func search(
        _ query: String, limit: Int, frecency: FrecencyStore?, frecencyWeight: Double = 1, now: Date = Date()
    ) -> [EmojiMatch] {
        guard limit > 0 else { return [] }
        let queryWords = Self.words(in: query).words
        guard !queryWords.isEmpty else { return browse(limit: limit, frecency: frecency, now: now) }

        let normalizedQuery = queryWords.joined(separator: " ")
        var candidates: [(index: Int, score: Double)] = []
        for (index, entry) in entries.enumerated() {
            if let score = Self.score(queryWords, normalizedQuery, entry) {
                candidates.append((index, score))
            }
        }
        if let frecency, !candidates.isEmpty {
            let scores = frecency.scores(for: candidates.map { Self.frecencyID(for: entries[$0.index].emoji) }, now: now)
            for position in candidates.indices where scores[position] > 0 {
                candidates[position].score += min(150, frecencyWeight * 40 * log(1 + scores[position]))
            }
        }
        candidates.sort { $0.score != $1.score ? $0.score > $1.score : $0.index < $1.index }
        return candidates.prefix(limit).map { candidate in
            let entry = entries[candidate.index]
            let details = Self.details(queryWords, entry)
            return EmojiMatch(entry: entry, score: candidate.score, titlePositions: details.positions, matchedKeyword: details.keyword)
        }
    }

    /// The frecent emoji, most frecent first, then the rest in data order.
    private func browse(limit: Int, frecency: FrecencyStore?, now: Date) -> [EmojiMatch] {
        var frecent: [(index: Int, score: Double)] = []
        if let frecency {
            let scores = frecency.scores(for: entries.map { Self.frecencyID(for: $0.emoji) }, now: now)
            for (index, score) in scores.enumerated() where score > 0 {
                frecent.append((index, score))
            }
            frecent.sort { $0.score != $1.score ? $0.score > $1.score : $0.index < $1.index }
        }
        var result = frecent.prefix(limit).map {
            EmojiMatch(entry: entries[$0.index], score: $0.score, titlePositions: [], matchedKeyword: nil)
        }
        let shown = Set(result.map(\.entry.order))
        for entry in entries where !shown.contains(entry.order) {
            guard result.count < limit else { break }
            result.append(EmojiMatch(entry: entry, score: 0, titlePositions: [], matchedKeyword: nil))
        }
        return result
    }

    /// Nil unless every query word starts a name or keyword word. Each query word scores 4 for an
    /// exact name word, 3 for a name-word prefix, 2 for an exact keyword and 1 for a keyword
    /// prefix; the average, times 100, is the base. The whole query equal to the name adds 1,000.
    /// A last query word equal to the name's last word, usually its head noun, adds 30, so "heart"
    /// lists hearts before "heart suit"; the name starting with the query adds 10. An exact keyword
    /// that a name word outscored adds a little, and each name word takes a little off, so shorter
    /// names win ties.
    static func score(_ queryWords: [String], _ normalizedQuery: String, _ entry: EmojiEntry) -> Double? {
        var total = 0
        var exactKeywords = 0
        for word in queryWords {
            var nameClass = 0
            for nameWord in entry.nameWords {
                if nameWord == word {
                    nameClass = 4
                    break
                }
                if nameClass == 0, nameWord.hasPrefix(word) { nameClass = 3 }
            }
            // Keywords never repeat a name word, so an exact name word needs no keyword pass.
            var keywordClass = 0
            if nameClass < 4 {
                for keyword in entry.keywords {
                    if keyword == word {
                        keywordClass = 2
                        break
                    }
                    if nameClass == 0, keywordClass == 0, keyword.hasPrefix(word) { keywordClass = 1 }
                }
            }
            guard nameClass > 0 || keywordClass > 0 else { return nil }
            total += max(nameClass, keywordClass)
            if nameClass > 0, keywordClass == 2 { exactKeywords += 1 }
        }
        let count = Double(queryWords.count)
        var score = 100 * Double(total) / count + 20 * Double(exactKeywords) / count
        if entry.normalizedName == normalizedQuery {
            score += 1_000
        } else {
            if entry.nameWords.last == queryWords.last { score += 30 }
            if entry.normalizedName.hasPrefix(normalizedQuery) { score += 10 }
        }
        return score - 2 * Double(min(entry.nameWords.count, 20))
    }

    /// The highlight positions of the matched name words, and the keyword shown when a query word
    /// matched only keywords.
    static func details(_ queryWords: [String], _ entry: EmojiEntry) -> (positions: [Int], keyword: String?) {
        var positions = Set<Int>()
        var keyword: String?
        let characters = Array(entry.name)
        for word in queryWords {
            var matched: Int?
            for (index, nameWord) in entry.nameWords.enumerated() {
                if nameWord == word {
                    matched = index
                    break
                }
                if matched == nil, nameWord.hasPrefix(word) { matched = index }
            }
            if let matched {
                // As many characters as the query word has, within the name word.
                var offset = entry.nameWordOffsets[matched]
                var remaining = word.count
                while remaining > 0, offset < characters.count, characters[offset].isLetter || characters[offset].isNumber {
                    positions.insert(offset)
                    offset += 1
                    remaining -= 1
                }
            } else if keyword == nil {
                keyword = entry.keywords.first { $0 == word } ?? entry.keywords.first { $0.hasPrefix(word) }
            }
        }
        return (positions.sorted(), keyword)
    }

    /// Lowercase, diacritic-folded runs of letters and digits, and each run's `Character` offset.
    static func words(in text: String) -> (words: [String], offsets: [Int]) {
        var words: [String] = []
        var offsets: [Int] = []
        var current = ""
        var start = 0
        for (offset, character) in text.enumerated() {
            if character.isLetter || character.isNumber {
                if current.isEmpty { start = offset }
                current.append(character)
            } else if !current.isEmpty {
                words.append(fold(current))
                offsets.append(start)
                current = ""
            }
        }
        if !current.isEmpty {
            words.append(fold(current))
            offsets.append(start)
        }
        return (words, offsets)
    }

    /// The generator folds keywords the same way.
    private static func fold(_ word: String) -> String {
        word.utf8.allSatisfy { $0 < 0x80 }
            ? word.lowercased()
            : word.folding(options: [.caseInsensitive, .diacriticInsensitive], locale: nil)
    }
}
