import AppKit
import Carbon.HIToolbox
import Core
import CoreGraphics

/// Pure insertion decisions.
enum InsertPlanner {
    /// One synthetic key event carries at most this many UTF-16 units.
    static let maxUnitsPerEvent = 20

    /// Text with a newline is always pasted: a typed Enter would run a terminal command or send a
    /// chat message. Otherwise the per-app override, then `settings.method`.
    static func method(for text: String, bundleID: String?, settings: InsertSettings) -> InsertMethod {
        if text.contains(where: \.isNewline) { return .paste }
        if let bundleID, let method = settings.apps[bundleID] { return method }
        return settings.method
    }

    /// Chunks of up to `chunkSize` grapheme clusters and at most `maxUnits` UTF-16 units, never
    /// splitting a cluster, except one that alone exceeds `maxUnits`, which is split between
    /// Unicode scalars (so never inside a surrogate pair).
    static func typingChunks(_ text: String, chunkSize: Int, maxUnits: Int = maxUnitsPerEvent) -> [String] {
        let size = max(1, chunkSize)
        var chunks: [String] = []
        var pending = ""
        var pendingCharacters = 0
        var pendingUnits = 0

        func flush() {
            guard !pending.isEmpty else { return }
            chunks.append(pending)
            pending = ""
            pendingCharacters = 0
            pendingUnits = 0
        }

        for character in text {
            let units = character.utf16.count
            if units > maxUnits {
                flush()
                var piece = String.UnicodeScalarView()
                var pieceUnits = 0
                for scalar in character.unicodeScalars {
                    let width = UTF16.width(scalar)
                    if pieceUnits + width > maxUnits, !piece.isEmpty {
                        chunks.append(String(piece))
                        piece = String.UnicodeScalarView()
                        pieceUnits = 0
                    }
                    piece.append(scalar)
                    pieceUnits += width
                }
                if !piece.isEmpty { chunks.append(String(piece)) }
                continue
            }
            if pendingCharacters >= size || pendingUnits + units > maxUnits { flush() }
            pending.append(character)
            pendingCharacters += 1
            pendingUnits += units
        }
        flush()
        return chunks
    }
}

public enum InsertAbort: String, Sendable {
    /// Another app came to the front, or one of our own windows has the keyboard.
    case targetChanged
    /// The caller withdrew permission (the screen locked or slept).
    case blocked
    case cancelled
}

public struct InsertResult: Sendable {
    public var method: InsertMethod?
    /// For paste: whether the previous clipboard was put back.
    public var restored: Bool?
    /// Time spent waiting for modifiers to be released.
    public var modifierWait: TimeInterval
    /// Set when nothing, or not everything, was inserted.
    public var aborted: InsertAbort?
    /// When typing stopped part-way: the text that was not typed.
    public var remainder: String?
}

/// Types or pastes text into the frontmost app. Every event it posts carries
/// `DictationConstants.eventUserData`, so the key monitor ignores it.
///
/// Before the paste and before every typed chunk it checks again that the target is frontmost,
/// that none of alauncher's own windows (TextPanel, launcher) has the keyboard, that the caller
/// still allows it (`isAllowed`), and that the task isn't cancelled. Typing yields to the main
/// actor every few chunks, so those checks see app switches and Esc even with no delay.
@MainActor
final class Inserter {
    static let shared = Inserter()

    static let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    static let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
    /// Largest clipboard we snapshot and restore.
    static let snapshotByteLimit = 16 << 20
    static let modifierWaitLimit: TimeInterval = 2
    /// With no typing delay, yield to the main actor after this many chunks.
    static let yieldInterval = 32
    private static let promisedTypes: Set<String> = [
        "com.apple.pasteboard.promised-file-url",
        "com.apple.pasteboard.promised-file-content-type",
        "com.apple.pasteboard.promised-suggested-file-name",
        "com.apple.NSFilePromiseItemMetaData",
        "NSPromiseContentsPboardType",
    ]
    private static let heldModifierMask: CGEventFlags = [.maskCommand, .maskAlternate, .maskControl, .maskShift, .maskSecondaryFn]

    private let log = Log.main
    private var cachedVKeyCode: CGKeyCode?
    private var inputSourceObserver: NSObjectProtocol?

    private init() {
        let name = Notification.Name(kTISNotifySelectedKeyboardInputSourceChanged as String)
        inputSourceObserver = DistributedNotificationCenter.default().addObserver(forName: name, object: nil, queue: .main) { _ in
            MainActor.assumeIsolated { Inserter.shared.cachedVKeyCode = nil }
        }
    }

    /// False when macOS won't let us post events (the signed app lacks Accessibility).
    var canPostEvents: Bool { CGPreflightPostEventAccess() }

    /// Inserts into `targetPID`'s app, which must stay frontmost; nil means whatever app is
    /// frontmost once modifiers are released (it must then stay frontmost).
    func insert(
        _ text: String, targetPID: pid_t?, settings: InsertSettings, isAllowed: () -> Bool = { true }
    ) async -> InsertResult {
        var result = InsertResult(modifierWait: await waitForModifierRelease())
        if Task.isCancelled {
            result.aborted = .cancelled
            return result
        }
        guard isAllowed() else {
            result.aborted = .blocked
            return result
        }
        guard let front = NSWorkspace.shared.frontmostApplication, targetPID == nil || front.processIdentifier == targetPID,
              !ownWindowIsKey() else {
            result.aborted = .targetChanged
            return result
        }
        let pid = front.processIdentifier
        let method = InsertPlanner.method(for: text, bundleID: front.bundleIdentifier, settings: settings)
        result.method = method
        switch method {
        case .type:
            (result.aborted, result.remainder) = await type(
                text, targetPID: pid, chunkSize: settings.typeChunk,
                delay: settings.typeDelay.timeInterval ?? 0, isAllowed: isAllowed
            )
        case .paste:
            (result.restored, result.aborted) = await paste(text, targetPID: pid, settings: settings, isAllowed: isAllowed)
        }
        return result
    }

    /// Whether `pid` is still frontmost and none of our windows has the keyboard.
    private func targetIsFront(_ pid: pid_t) -> Bool {
        NSWorkspace.shared.frontmostApplication?.processIdentifier == pid && !ownWindowIsKey()
    }

    private func ownWindowIsKey() -> Bool {
        NSApp.windows.contains { $0.isVisible && $0.isKeyWindow }
    }

    private func abortReason(_ pid: pid_t, _ isAllowed: () -> Bool) -> InsertAbort? {
        if Task.isCancelled { return .cancelled }
        if !isAllowed() { return .blocked }
        if !targetIsFront(pid) { return .targetChanged }
        return nil
    }

    /// Polls until no modifier is physically held, for up to 2 s: a synthetic Cmd+V while
    /// Option is down would arrive as Cmd+Option+V. Continues anyway after the limit; returns
    /// early when cancelled.
    private func waitForModifierRelease() async -> TimeInterval {
        let start = Date()
        while !CGEventSource.flagsState(.combinedSessionState).intersection(Self.heldModifierMask).isEmpty {
            if Date().timeIntervalSince(start) >= Self.modifierWaitLimit {
                log("insert: modifiers still held after \(Self.modifierWaitLimit) s, inserting anyway")
                break
            }
            do {
                try await Task.sleep(nanoseconds: 15_000_000)
            } catch {
                break
            }
        }
        return Date().timeIntervalSince(start)
    }

    /// Posts the chunks from the main actor. Returns why it stopped early, with the untyped rest.
    private func type(
        _ text: String, targetPID: pid_t, chunkSize: Int, delay: TimeInterval, isAllowed: () -> Bool
    ) async -> (InsertAbort?, String?) {
        let chunks = InsertPlanner.typingChunks(text, chunkSize: chunkSize)
        let source = CGEventSource(stateID: .hidSystemState)
        source?.userData = DictationConstants.eventUserData
        for (index, chunk) in chunks.enumerated() {
            if delay == 0, index > 0, index % Self.yieldInterval == 0 { await Task.yield() }
            if let reason = abortReason(targetPID, isAllowed) {
                if index > 0 { log("insert: stopped typing after \(index) of \(chunks.count) chunks (\(reason.rawValue))") }
                return (reason, chunks[index...].joined())
            }
            let units = Array(chunk.utf16)
            for down in [true, false] {
                guard let event = CGEvent(keyboardEventSource: source, virtualKey: 0, keyDown: down) else { continue }
                event.flags = []
                event.setIntegerValueField(.eventSourceUserData, value: DictationConstants.eventUserData)
                units.withUnsafeBufferPointer {
                    event.keyboardSetUnicodeString(stringLength: $0.count, unicodeString: $0.baseAddress)
                }
                event.post(tap: .cghidEventTap)
            }
            if delay > 0 {
                do {
                    try await Task.sleep(nanoseconds: UInt64(min(delay, 1) * 1_000_000_000))
                } catch {
                    let rest = chunks[(index + 1)...].joined()
                    return (.cancelled, rest.isEmpty ? nil : rest)
                }
            }
        }
        return (nil, nil)
    }

    /// Snapshot, write the text with the transient markers, Cmd+V, then restore the snapshot after
    /// `pasteRestoreDelay` if the clipboard is still ours. Once Cmd+V is posted the restore always
    /// waits the full delay, even when cancelled: the target reads the clipboard asynchronously.
    private func paste(
        _ text: String, targetPID: pid_t, settings: InsertSettings, isAllowed: () -> Bool
    ) async -> (restored: Bool?, abort: InsertAbort?) {
        let pasteboard = NSPasteboard.general
        var snapshot: [NSPasteboardItem]?
        var skipReason: String?
        if settings.pasteRestore {
            (snapshot, skipReason) = Self.snapshot(pasteboard)
        }
        // A big snapshot takes a moment: check again right before touching the clipboard.
        if let reason = abortReason(targetPID, isAllowed) { return (nil, reason) }

        pasteboard.clearContents()
        let item = NSPasteboardItem()
        item.setString(text, forType: .string)
        item.setData(Data(), forType: Self.transientType)
        item.setData(Data(), forType: Self.autoGeneratedType)
        pasteboard.writeObjects([item])
        let ours = pasteboard.changeCount
        postCommandV()

        guard settings.pasteRestore else { return (false, nil) }
        guard let snapshot else {
            log("insert: clipboard not restored (\(skipReason ?? "no snapshot")); the dictation stays on it")
            return (false, nil)
        }
        await Self.sleepIgnoringCancellation(settings.pasteRestoreDelay.timeInterval ?? 0.25)
        guard pasteboard.changeCount == ours else {
            log("insert: clipboard changed during paste; not restoring")
            return (false, nil)
        }
        pasteboard.clearContents()
        if !snapshot.isEmpty {
            for item in snapshot { item.setData(Data(), forType: Self.transientType) }
            pasteboard.writeObjects(snapshot)
        }
        return (true, nil)
    }

    private static func sleepIgnoringCancellation(_ seconds: TimeInterval) async {
        await withCheckedContinuation { (continuation: CheckedContinuation<Void, Never>) in
            DispatchQueue.main.asyncAfter(deadline: .now() + max(0, seconds)) { continuation.resume() }
        }
    }

    /// Fresh copies of every item and type (retrieved items can't be written back), or nil with a
    /// reason when the clipboard can't be restored faithfully.
    static func snapshot(_ pasteboard: NSPasteboard) -> ([NSPasteboardItem]?, String?) {
        if #available(macOS 15.4, *) {
            // Reading would prompt (or fail) unless access is always allowed.
            guard pasteboard.accessBehavior == .alwaysAllow else { return (nil, "pasteboard access is not always-allow") }
        }
        var total = 0
        var copies: [NSPasteboardItem] = []
        for item in pasteboard.pasteboardItems ?? [] {
            let copy = NSPasteboardItem()
            for type in item.types {
                if promisedTypes.contains(type.rawValue) { return (nil, "promised data") }
                guard let data = item.data(forType: type) else { return (nil, "promised data") }
                total += data.count
                if total > snapshotByteLimit { return (nil, "larger than 16 MB") }
                copy.setData(data, forType: type)
            }
            copies.append(copy)
        }
        return (copies, nil)
    }

    private func postCommandV() {
        let keyCode = vKeyCode()
        let source = CGEventSource(stateID: .hidSystemState)
        source?.userData = DictationConstants.eventUserData
        for down in [true, false] {
            guard let event = CGEvent(keyboardEventSource: source, virtualKey: keyCode, keyDown: down) else { continue }
            event.flags = .maskCommand
            event.setIntegerValueField(.eventSourceUserData, value: DictationConstants.eventUserData)
            event.post(tap: .cghidEventTap)
        }
    }

    /// The key that types "v" in the current layout's Command layer (Dvorak-QWERTY ⌘ remaps it).
    private func vKeyCode() -> CGKeyCode {
        if let cachedVKeyCode { return cachedVKeyCode }
        let code = Self.lookUpVKeyCode() ?? CGKeyCode(kVK_ANSI_V)
        cachedVKeyCode = code
        return code
    }

    private static func lookUpVKeyCode() -> CGKeyCode? {
        guard let source = TISCopyCurrentKeyboardLayoutInputSource()?.takeRetainedValue(),
              let property = TISGetInputSourceProperty(source, kTISPropertyUnicodeKeyLayoutData) else { return nil }
        let layoutData = Unmanaged<CFData>.fromOpaque(property).takeUnretainedValue()
        guard let bytes = CFDataGetBytePtr(layoutData) else { return nil }
        let layout = UnsafeRawPointer(bytes).assumingMemoryBound(to: UCKeyboardLayout.self)
        let commandState = UInt32((cmdKey >> 8) & 0xFF)
        let keyboardType = UInt32(LMGetKbdType())
        for code in 0..<128 {
            var deadKeyState: UInt32 = 0
            var length = 0
            var characters = [UniChar](repeating: 0, count: 4)
            let status = UCKeyTranslate(
                layout, UInt16(code), UInt16(kUCKeyActionDown), commandState, keyboardType,
                OptionBits(kUCKeyTranslateNoDeadKeysBit), &deadKeyState, characters.count, &length, &characters
            )
            if status == noErr, length == 1, characters[0] == UniChar(0x76) { return CGKeyCode(code) }
        }
        return nil
    }
}
